"use client";

import { useEffect, useState, useRef } from "react";
import { CheckSquare, Plus, Clock, Sparkles, Trash2, CheckCircle2, BookOpen, Download, Calendar } from "lucide-react";
import { api } from "@/lib/api";
import PomodoroTimer from "@/components/PomodoroTimer";
import { downloadICS, CalendarEvent } from "@/lib/calendar-export";

export default function TasksPage() {
  const [tasks, setTasks] = useState<any[]>([]);
  const [reminders, setReminders] = useState<any[]>([]);
  const [studyPlans, setStudyPlans] = useState<any[]>([]);
  const [newTitle, setNewTitle] = useState("");
  const [newDue, setNewDue] = useState("2026-09-28");
  const [newPriority, setNewPriority] = useState("high");
  const [loading, setLoading] = useState(true);
  
  // Active study plan topic loaded into Pomodoro focus timer
  const [activePomodoroTopic, setActivePomodoroTopic] = useState<string>("Normalization & Functional Dependencies (1NF, 2NF, 3NF, BCNF)");
  const [activePomodoroMinutes, setActivePomodoroMinutes] = useState<number>(40);
  const [activePomodoroReason, setActivePomodoroReason] = useState<string>("Highest weightage in Module 3 syllabus; key question on BCNF decomposition.");
  const [activeLoadedTopic, setActiveLoadedTopic] = useState<string>("Normalization & Functional Dependencies (1NF, 2NF, 3NF, BCNF)");
  const [toastMessage, setToastMessage] = useState<string | null>(null);
  const timerSectionRef = useRef<HTMLDivElement | null>(null);

  // Helper to calculate duration in minutes
  const getDurationMinutes = (item: any): number => {
    if (item.duration_minutes && item.duration_minutes > 0) return item.duration_minutes;
    if (item.start_time && item.end_time) {
      try {
        const [sh, sm] = item.start_time.split(":").map(Number);
        const [eh, em] = item.end_time.split(":").map(Number);
        const diff = (eh * 60 + em) - (sh * 60 + sm);
        if (diff > 0) return diff;
      } catch (e) {}
    }
    return 40;
  };

  // Handler when user clicks "Load" on any study plan item
  const handleLoadItem = (item: any) => {
    const mins = getDurationMinutes(item);
    setActivePomodoroTopic(item.topic);
    setActivePomodoroMinutes(mins);
    setActivePomodoroReason(item.reason || "");
    setActiveLoadedTopic(item.topic);

    // Smoothly scroll to the Pomodoro Timer container so user sees it loaded instantly
    if (timerSectionRef.current) {
      timerSectionRef.current.scrollIntoView({ behavior: "smooth", block: "center" });
    }

    setToastMessage(`⚡ Loaded "${item.topic}" (${mins} Mins) into Focus Session!`);
    setTimeout(() => setToastMessage(null), 3000);
  };

  useEffect(() => {
    loadData();
  }, []);

  const loadData = async () => {
    try {
      setLoading(true);
      const [tRes, rRes, pRes] = await Promise.all([
        api.getTasks(),
        api.getReminders(),
        api.getStudyPlans()
      ]);
      setTasks(tRes.tasks || []);
      setReminders(rRes.reminders || []);
      setStudyPlans(pRes.study_plans || []);
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  const handleCreateTask = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!newTitle.trim()) return;
    try {
      await api.createTask({
        title: newTitle,
        due_date: newDue,
        priority: newPriority
      });
      setNewTitle("");
      loadData();
    } catch (e) {
      console.error(e);
    }
  };

  const handleToggleTask = async (task: any) => {
    try {
      const nextStatus = task.status === "completed" ? "pending" : "completed";
      await api.updateTask(task.id, { status: nextStatus });
      loadData();
    } catch (e) {
      console.error(e);
    }
  };

  // Export all study plan items and exams to standard .ICS calendar file
  const handleExportICS = () => {
    const events: CalendarEvent[] = [
      {
        title: "DBMS End-Term Exam (CS501)",
        description: "Official venue relocated to Room B-204 (Science & Tech Wing). Biometric reporting at 09:30 AM.",
        location: "Room B-204 (Science & Tech Block)",
        startDate: "2026-09-28",
        startTime: "10:00",
        durationMinutes: 180
      },
      {
        title: "DBMS Revision: Normalization & BCNF",
        description: "Prioritized study session generated by CampusFlow AI.",
        location: "Desk / Quiet Study",
        startDate: "2026-09-27",
        startTime: "19:00",
        durationMinutes: 40
      },
      {
        title: "DBMS Revision: Transactions & Strict 2PL",
        description: "Concurrency control & ACID anomalies.",
        location: "Desk / Quiet Study",
        startDate: "2026-09-27",
        startTime: "19:40",
        durationMinutes: 40
      }
    ];

    downloadICS("CampusFlow_Fall2026_Schedule.ics", events);
  };

  return (
    <div className="max-w-7xl mx-auto px-4 py-8 space-y-10">
      
      {/* Header with 1-Click Calendar Sync */}
      <div className="pb-6 border-b border-white/10 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl sm:text-3xl font-black text-white">Tasks, Reminders &amp; Study Execution</h1>
          <p className="text-xs text-slate-400 mt-1">
            Unified academic action board populated by CampusFlow AI and MCP tool actions.
          </p>
        </div>

        {/* 1-Click .ICS Export */}
        <button
          onClick={handleExportICS}
          className="flex items-center gap-2 px-4 py-2.5 rounded-xl font-bold text-xs bg-gradient-to-r from-emerald-500 to-teal-600 text-white shadow-lg shadow-emerald-500/20 hover:scale-105 transition-all"
          title="Download RFC 5545 iCalendar file for Google Calendar, Outlook, and Apple Calendar"
        >
          <Calendar className="w-4 h-4" />
          <span>Export to Calendar (.ICS)</span>
          <Download className="w-3.5 h-3.5" />
        </button>
      </div>

      {/* Toast Notification Banner */}
      {toastMessage && (
        <div className="p-3.5 rounded-2xl bg-cyan-950/80 border border-cyan-400 text-cyan-200 text-xs font-bold flex items-center justify-between shadow-lg shadow-cyan-500/20 animate-bounce">
          <div className="flex items-center gap-2">
            <Sparkles className="w-4 h-4 text-cyan-400 animate-spin" />
            <span>{toastMessage}</span>
          </div>
          <button 
            onClick={() => setToastMessage(null)}
            className="text-[10px] text-cyan-300 hover:text-white underline cursor-pointer"
          >
            Dismiss
          </button>
        </div>
      )}

      {/* Live Focus Pomodoro Execution Mode */}
      <div ref={timerSectionRef}>
        <PomodoroTimer 
          topic={activePomodoroTopic}
          defaultMinutes={activePomodoroMinutes}
          reason={activePomodoroReason}
        />
      </div>

      <div className="grid lg:grid-cols-12 gap-8 items-start">
        
        {/* Left: Tasks Management (7 cols) */}
        <div className="lg:col-span-7 space-y-6">
          
          {/* Create Task Form */}
          <form onSubmit={handleCreateTask} className="glass-panel p-5 rounded-2xl border border-white/10 space-y-3">
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-300">
              Quick Add Academic Task
            </h3>
            <div className="flex flex-col sm:flex-row gap-2">
              <input
                type="text"
                value={newTitle}
                onChange={(e) => setNewTitle(e.target.value)}
                placeholder="e.g. Revise Transactions Strict 2PL or submit CN report"
                className="flex-1 bg-slate-900/80 border border-white/10 rounded-xl px-3.5 py-2 text-xs text-white placeholder:text-slate-500 focus:outline-none focus:border-cyan-500/50"
              />
              <input
                type="date"
                value={newDue}
                onChange={(e) => setNewDue(e.target.value)}
                className="bg-slate-900/80 border border-white/10 rounded-xl px-3 py-2 text-xs text-slate-300 focus:outline-none"
              />
              <select
                value={newPriority}
                onChange={(e) => setNewPriority(e.target.value)}
                className="bg-slate-900/80 border border-white/10 rounded-xl px-3 py-2 text-xs text-slate-300 focus:outline-none"
              >
                <option value="low">Low</option>
                <option value="medium">Medium</option>
                <option value="high">High</option>
                <option value="urgent">Urgent</option>
              </select>
              <button
                type="submit"
                className="px-4 py-2 rounded-xl bg-cyan-500 hover:bg-cyan-400 text-black font-bold text-xs flex items-center justify-center gap-1 shadow-md shadow-cyan-500/20"
              >
                <Plus className="w-3.5 h-3.5" />
                Add
              </button>
            </div>
          </form>

          {/* Task List */}
          <div className="glass-panel p-6 rounded-3xl border border-white/10 space-y-3">
            <div className="flex items-center justify-between border-b border-white/5 pb-3">
              <h3 className="text-xs font-bold uppercase tracking-wider text-slate-200 flex items-center gap-2">
                <CheckSquare className="w-4 h-4 text-cyan-400" />
                Active Tasks ({tasks.filter(t => t.status === "pending").length})
              </h3>
            </div>

            {loading ? (
              <p className="text-xs text-slate-400">Loading tasks...</p>
            ) : tasks.length === 0 ? (
              <p className="text-xs text-slate-400">No active tasks. Say &ldquo;Prepare me for tomorrow&rdquo; to auto-generate tasks.</p>
            ) : (
              <div className="space-y-2">
                {tasks.map((task) => {
                  const isDone = task.status === "completed";
                  return (
                    <div
                      key={task.id}
                      onClick={() => handleToggleTask(task)}
                      className={`p-3.5 rounded-xl border flex items-center justify-between cursor-pointer transition-all select-none ${
                        isDone
                          ? "bg-slate-900/40 border-white/5 opacity-60 line-through"
                          : "bg-slate-900/80 border-white/5 hover:border-cyan-500/30"
                      }`}
                    >
                      <div className="flex items-center gap-3">
                        <div className={`w-4 h-4 rounded border flex items-center justify-center ${
                          isDone ? "bg-cyan-500 border-cyan-400 text-black" : "border-slate-600"
                        }`}>
                          {isDone && <CheckCircle2 className="w-3.5 h-3.5" />}
                        </div>
                        <div>
                          <h4 className="text-xs font-semibold text-white">{task.title}</h4>
                          <p className="text-[10px] text-slate-400 mt-0.5">Due: {task.due_date || "No date"}</p>
                        </div>
                      </div>

                      <span className={`text-[9px] uppercase font-bold px-2 py-0.5 rounded border ${
                        task.priority === "urgent" 
                          ? "bg-rose-500/20 text-rose-300 border-rose-500/30"
                          : task.priority === "high"
                          ? "bg-amber-500/20 text-amber-300 border-amber-500/30"
                          : "bg-slate-800 text-slate-400 border-slate-700"
                      }`}>
                        {task.priority}
                      </span>
                    </div>
                  );
                })}
              </div>
            )}
          </div>

          {/* AI Generated Study Plans */}
          <div className="glass-panel p-6 rounded-3xl border border-white/10 space-y-4">
            <div className="flex items-center gap-2 border-b border-white/5 pb-3">
              <BookOpen className="w-4 h-4 text-purple-400" />
              <h3 className="text-xs font-bold uppercase tracking-wider text-slate-200">
                Personalized AI Study Plans
              </h3>
            </div>

            {studyPlans.length === 0 ? (
              <p className="text-xs text-slate-400">No study plans created yet. Ask CampusFlow to build one!</p>
            ) : (
              <div className="space-y-4">
                {studyPlans.map((plan, i) => (
                  <div key={i} className="p-4 rounded-2xl bg-purple-950/20 border border-purple-500/30 space-y-3">
                    <div className="flex items-center justify-between">
                      <div>
                        <h4 className="text-xs font-bold text-purple-200">{plan.subject}</h4>
                        <span className="text-[10px] text-slate-400">Exam: {plan.exam_date} &bull; {plan.target_hours} Hours Target</span>
                      </div>
                      <span className="text-[10px] px-2 py-0.5 rounded bg-purple-500/20 text-purple-300 font-mono font-bold">
                        {plan.status}
                      </span>
                    </div>

                    <div className="space-y-2.5">
                      {plan.items?.map((item: any, j: number) => {
                        const isCurrentActive = activeLoadedTopic === item.topic;
                        return (
                          <div 
                            key={j} 
                            onClick={() => handleLoadItem(item)}
                            className={`p-3 rounded-2xl border flex items-center justify-between text-xs cursor-pointer transition-all duration-200 ${
                              isCurrentActive
                                ? "bg-purple-900/40 border-cyan-400 ring-2 ring-cyan-500/30 shadow-lg shadow-cyan-500/10"
                                : "bg-black/40 border-white/5 hover:border-purple-400/40 hover:bg-black/60"
                            }`}
                            title="Click to load into Pomodoro Focus Session"
                          >
                            <div className="pr-3">
                              <span className="font-semibold text-white flex items-center gap-1.5">
                                <Sparkles className={`w-3.5 h-3.5 ${isCurrentActive ? "text-cyan-400 animate-spin" : "text-purple-400"}`} />
                                {item.topic}
                              </span>
                              <p className="text-[10px] text-slate-400 mt-0.5">{item.reason}</p>
                            </div>
                            <div className="flex items-center gap-2.5 shrink-0">
                              <span className="text-[11px] font-mono text-cyan-300 font-bold bg-cyan-950/60 px-2 py-0.5 rounded border border-cyan-800/40">
                                {item.start_time} &ndash; {item.end_time}
                              </span>
                              {isCurrentActive ? (
                                <span className="text-[10px] font-bold text-emerald-300 bg-emerald-500/20 px-2.5 py-1 rounded-lg border border-emerald-400/40 flex items-center gap-1 shadow-sm">
                                  <CheckCircle2 className="w-3 h-3 text-emerald-400" />
                                  Active
                                </span>
                              ) : (
                                <button
                                  type="button"
                                  onClick={(e) => {
                                    e.stopPropagation();
                                    handleLoadItem(item);
                                  }}
                                  className="text-[10px] font-bold text-white bg-gradient-to-r from-purple-600 to-indigo-600 hover:from-purple-500 hover:to-indigo-500 px-3 py-1 rounded-lg border border-purple-400/40 shadow-sm shadow-purple-500/20 transition-all cursor-pointer hover:scale-105 active:scale-95"
                                >
                                  Load
                                </button>
                              )}
                            </div>
                          </div>
                        );
                      })}
                    </div>

                    {plan.why_explanation && (
                      <p className="text-[11px] text-purple-200/90 italic pt-1 border-t border-purple-500/20">
                        &ldquo;{plan.why_explanation}&rdquo;
                      </p>
                    )}
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

        {/* Right: Active Reminders (5 cols) */}
        <div className="lg:col-span-5 space-y-6">
          <div className="glass-panel p-6 rounded-3xl border border-white/10 space-y-4">
            <div className="flex items-center gap-2 border-b border-white/5 pb-3">
              <Clock className="w-4 h-4 text-cyan-400" />
              <h3 className="text-xs font-bold uppercase tracking-wider text-slate-200">
                Scheduled Reminders
              </h3>
            </div>

            {reminders.length === 0 ? (
              <p className="text-xs text-slate-400">No active reminders.</p>
            ) : (
              <div className="space-y-2.5">
                {reminders.map((rem, i) => (
                  <div key={i} className="p-3.5 rounded-2xl bg-slate-900/70 border border-white/5 space-y-1">
                    <div className="flex items-center justify-between">
                      <span className="text-[10px] uppercase font-mono px-2 py-0.5 rounded bg-cyan-950 text-cyan-300 font-bold border border-cyan-800">
                        {rem.type}
                      </span>
                      <span className="text-xs font-mono text-cyan-400 font-bold">
                        {rem.time} IST
                      </span>
                    </div>
                    <h5 className="text-xs font-bold text-white">{rem.title}</h5>
                    <p className="text-[10px] text-slate-400">Date: {rem.date} &bull; Created by {rem.created_by}</p>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>

      </div>
    </div>
  );
}
